version: "3"

services:
  node1:
    environment:
      GENESIS_NODE:
        1
      FILES:
        "src/test/resources/lastBlock1.txt;src/test/resources/lastBlock2.txt;src/test/resources/lastBlock2.txt"
    build:
      context: .
    command: --type 1

  node2:
    environment:
      GENESIS_NODE:
        1
      FILES:
        "src/test/resources/lastBlock1.txt;src/test/resources/lastBlock2.txt;src/test/resources/lastBlock2.txt"
    build:
      context: .
    command: --type 2

  node3:
    environment:
      GENESIS_NODE:
        1
      FILES:
        "src/test/resources/lastBlock1.txt;src/test/resources/lastBlock2.txt;src/test/resources/lastBlock2.txt"
    build:
      context: .
    command: --type 3