version: "3"

services:
  node1:
    environment:
      GENESIS_NODE:
        1
      FILES:
        "src/test/resources/lastBlock1.txt;src/test/resources/lastBlock2.txt;src/test/resources/lastBlock2.txt"
    build:
      context: .
    entrypoint: java -jar ./app/blockchain-all.jar
    command: --type 1

  node2:
    environment:
      GENESIS_NODE:
        1
      FILES:
        "src/test/resources/lastBlock1.txt;src/test/resources/lastBlock2.txt;src/test/resources/lastBlock2.txt"
    build:
      context: .
    entrypoint: java -jar ./app/blockchain-all.jar
    command: --type 1

  node3:
    environment:
      GENESIS_NODE:
        1
      FILES:
        "src/test/resources/lastBlock1.txt;src/test/resources/lastBlock2.txt;src/test/resources/lastBlock2.txt"
    build:
      context: .
    entrypoint: java -jar ./app/blockchain-all.jar
    command: --type 1