version: "3"

services:
  node1:
    environment:
      NODE_TYPE:
        1
      GENESIS_NODE:
        1
      FILES:
        src/test/resources/lastBlock1.txt,src/test/resources/lastBlock2.txt,src/test/resources/lastBlock3.txt
    build:
      context: .
    command: ""

  node2:
    environment:
      NODE_TYPE:
        2
      GENESIS_NODE:
        1
      FILES:
        src/test/resources/lastBlock1.txt,src/test/resources/lastBlock2.txt,src/test/resources/lastBlock3.txt
    build:
      context: .
    command: ""

  node3:
    environment:
      NODE_TYPE:
        3
      GENESIS_NODE:
        1
      FILES:
        src/test/resources/lastBlock1.txt,src/test/resources/lastBlock2.txt,src/test/resources/lastBlock3.txt
    build:
      context: .
    command: ""