name: run-tests-task
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:


jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@HEAD
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test -i
          gradle-version: 7.4.2